### ISSUE TITLE
Using Rule keyword causes no-files-without-scenarios check to fail

### ISSUE THREAD

**Issue by dsm2005** [gherkin-lint/gherkin-lint#254]
See tim-yao's [comment](https://github.com/vsiakka/gherkin-lint/issues/233#issuecomment-848390570) in #233 

> Rule will cause no-files-without-scenarios fail:
> 
> Feature file does not have any Scenarios    no-files-without-scenarios
> Basically that means, most of lint won't work if I use Rule in my feature.

**Comment by tim-yao** [comment]
`keywords-in-logical-order` also fails if `Rule` is in use.

**Comment by cjacquinot** [comment]
Rule present and no-dupe-scenario-names enable, the duplicated scenario names are not found too

**Comment by dmayerdesign** [comment]
`max-scenarios-per-file` also seems to not support Rule — failing for me like this:
```
(node:15675) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'examples' of null
    at /Users/dmayer/code/all-java/node_modules/gherkin-lint/dist/rules/max-scenarios-per-file.js:25:31
    at Array.forEach (<anonymous>)
    at Object.run (/Users/dmayer/code/all-java/node_modules/gherkin-lint/dist/rules/max-scenarios-per-file.js:22:20)
    at /Users/dmayer/code/all-java/node_modules/gherkin-lint/dist/rules.js:46:26
    at Array.forEach (<anonymous>)
    at Object.runAllEnabledRules (/Users/dmayer/code/all-java/node_modules/gherkin-lint/dist/rules.js:41:22)
    at readAndParseFile.then.perFileErrors (/Users/dmayer/code/all-java/node_modules/gherkin-lint/dist/linter.js:74:29)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 24)

```
